'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On

Imports System
Imports System.ComponentModel
Imports System.Diagnostics
Imports System.Web.Services
Imports System.Web.Services.Protocols
Imports System.Xml.Serialization

'
'This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
'
Namespace HanaService
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Web.Services.WebServiceBindingAttribute(Name:="SI_OS_CONSULTA_DATOS_TRABAJADORESBinding", [Namespace]:="https://www.ferreycorp.com.pe/HCM_LEGACY/ConsultaTrabajadores/HCM_PT-I-004")>  _
    Partial Public Class SI_OS_CONSULTA_DATOS_TRABAJADORESService
        Inherits System.Web.Services.Protocols.SoapHttpClientProtocol
        
        Private SI_OS_CONSULTA_DATOS_TRABAJADORESOperationCompleted As System.Threading.SendOrPostCallback
        
        Private useDefaultCredentialsSetExplicitly As Boolean
        
        '''<remarks/>
        Public Sub New()
            MyBase.New
            Me.Url = Global.ServicioExterno.My.MySettings.Default.ServicioExterno_HanaService_SI_OS_CONSULTA_DATOS_TRABAJADORESService
            If (Me.IsLocalFileSystemWebService(Me.Url) = true) Then
                Me.UseDefaultCredentials = true
                Me.useDefaultCredentialsSetExplicitly = false
            Else
                Me.useDefaultCredentialsSetExplicitly = true
            End If
        End Sub
        
        Public Shadows Property Url() As String
            Get
                Return MyBase.Url
            End Get
            Set
                If (((Me.IsLocalFileSystemWebService(MyBase.Url) = true)  _
                            AndAlso (Me.useDefaultCredentialsSetExplicitly = false))  _
                            AndAlso (Me.IsLocalFileSystemWebService(value) = false)) Then
                    MyBase.UseDefaultCredentials = false
                End If
                MyBase.Url = value
            End Set
        End Property
        
        Public Shadows Property UseDefaultCredentials() As Boolean
            Get
                Return MyBase.UseDefaultCredentials
            End Get
            Set
                MyBase.UseDefaultCredentials = value
                Me.useDefaultCredentialsSetExplicitly = true
            End Set
        End Property
        
        '''<remarks/>
        Public Event SI_OS_CONSULTA_DATOS_TRABAJADORESCompleted As SI_OS_CONSULTA_DATOS_TRABAJADORESCompletedEventHandler
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://sap.com/xi/WebService/soap1.1", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Bare)>  _
        Public Function SI_OS_CONSULTA_DATOS_TRABAJADORES(<System.Xml.Serialization.XmlElementAttribute([Namespace]:="https://www.ferreycorp.com.pe/HCM_LEGACY/ConsultaTrabajadores/HCM_PT-I-004")> ByVal MT_CONSULTA_DATOSTRABAJADORES_REQ As DT_CONSULTA_DATOSTRABAJADORES_REQ) As <System.Xml.Serialization.XmlElementAttribute("MT_CONSULTA_DATOSTRABAJADORES_RES", [Namespace]:="https://www.ferreycorp.com.pe/HCM_LEGACY/ConsultaTrabajadores/HCM_PT-I-004")> DT_CONSULTA_DATOSTRABAJADORES_RES
            Dim results() As Object = Me.Invoke("SI_OS_CONSULTA_DATOS_TRABAJADORES", New Object() {MT_CONSULTA_DATOSTRABAJADORES_REQ})
            Return CType(results(0),DT_CONSULTA_DATOSTRABAJADORES_RES)
        End Function
        
        '''<remarks/>
        Public Overloads Sub SI_OS_CONSULTA_DATOS_TRABAJADORESAsync(ByVal MT_CONSULTA_DATOSTRABAJADORES_REQ As DT_CONSULTA_DATOSTRABAJADORES_REQ)
            Me.SI_OS_CONSULTA_DATOS_TRABAJADORESAsync(MT_CONSULTA_DATOSTRABAJADORES_REQ, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub SI_OS_CONSULTA_DATOS_TRABAJADORESAsync(ByVal MT_CONSULTA_DATOSTRABAJADORES_REQ As DT_CONSULTA_DATOSTRABAJADORES_REQ, ByVal userState As Object)
            If (Me.SI_OS_CONSULTA_DATOS_TRABAJADORESOperationCompleted Is Nothing) Then
                Me.SI_OS_CONSULTA_DATOS_TRABAJADORESOperationCompleted = AddressOf Me.OnSI_OS_CONSULTA_DATOS_TRABAJADORESOperationCompleted
            End If
            Me.InvokeAsync("SI_OS_CONSULTA_DATOS_TRABAJADORES", New Object() {MT_CONSULTA_DATOSTRABAJADORES_REQ}, Me.SI_OS_CONSULTA_DATOS_TRABAJADORESOperationCompleted, userState)
        End Sub
        
        Private Sub OnSI_OS_CONSULTA_DATOS_TRABAJADORESOperationCompleted(ByVal arg As Object)
            If (Not (Me.SI_OS_CONSULTA_DATOS_TRABAJADORESCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent SI_OS_CONSULTA_DATOS_TRABAJADORESCompleted(Me, New SI_OS_CONSULTA_DATOS_TRABAJADORESCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        Public Shadows Sub CancelAsync(ByVal userState As Object)
            MyBase.CancelAsync(userState)
        End Sub
        
        Private Function IsLocalFileSystemWebService(ByVal url As String) As Boolean
            If ((url Is Nothing)  _
                        OrElse (url Is String.Empty)) Then
                Return false
            End If
            Dim wsUri As System.Uri = New System.Uri(url)
            If ((wsUri.Port >= 1024)  _
                        AndAlso (String.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) = 0)) Then
                Return true
            End If
            Return false
        End Function
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="https://www.ferreycorp.com.pe/HCM_LEGACY/ConsultaTrabajadores/HCM_PT-I-004")>  _
    Partial Public Class DT_CONSULTA_DATOSTRABAJADORES_REQ
        
        Private sociedadField As String
        
        Private codigoField As String
        
        Private numeroDocumentoField As String
        
        Private sexoField As String
        
        Private estadoCivilField As String
        
        Private fechaIngresoField As Date
        
        Private fechaIngresoFieldSpecified As Boolean
        
        Private unidad_OrganizatField As String
        
        Private centroCostoField As String
        
        Private divisionPersonaField As String
        
        Private subdivisionPersonaField As String
        
        Private posicionField As String
        
        Private areaPersonalField As String
        
        Private nombreField As String
        
        Private codigoAutoGenField As String
        
        Private fechaCumpleField As String
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property Sociedad() As String
            Get
                Return Me.sociedadField
            End Get
            Set
                Me.sociedadField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property Codigo() As String
            Get
                Return Me.codigoField
            End Get
            Set
                Me.codigoField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property NumeroDocumento() As String
            Get
                Return Me.numeroDocumentoField
            End Get
            Set
                Me.numeroDocumentoField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property Sexo() As String
            Get
                Return Me.sexoField
            End Get
            Set
                Me.sexoField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property EstadoCivil() As String
            Get
                Return Me.estadoCivilField
            End Get
            Set
                Me.estadoCivilField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType:="date")>  _
        Public Property FechaIngreso() As Date
            Get
                Return Me.fechaIngresoField
            End Get
            Set
                Me.fechaIngresoField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()>  _
        Public Property FechaIngresoSpecified() As Boolean
            Get
                Return Me.fechaIngresoFieldSpecified
            End Get
            Set
                Me.fechaIngresoFieldSpecified = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property Unidad_Organizat() As String
            Get
                Return Me.unidad_OrganizatField
            End Get
            Set
                Me.unidad_OrganizatField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property CentroCosto() As String
            Get
                Return Me.centroCostoField
            End Get
            Set
                Me.centroCostoField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property DivisionPersona() As String
            Get
                Return Me.divisionPersonaField
            End Get
            Set
                Me.divisionPersonaField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property SubdivisionPersona() As String
            Get
                Return Me.subdivisionPersonaField
            End Get
            Set
                Me.subdivisionPersonaField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property Posicion() As String
            Get
                Return Me.posicionField
            End Get
            Set
                Me.posicionField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property AreaPersonal() As String
            Get
                Return Me.areaPersonalField
            End Get
            Set
                Me.areaPersonalField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property Nombre() As String
            Get
                Return Me.nombreField
            End Get
            Set
                Me.nombreField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property CodigoAutoGen() As String
            Get
                Return Me.codigoAutoGenField
            End Get
            Set
                Me.codigoAutoGenField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property FechaCumple() As String
            Get
                Return Me.fechaCumpleField
            End Get
            Set
                Me.fechaCumpleField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="https://www.ferreycorp.com.pe/HCM_LEGACY/ConsultaTrabajadores/HCM_PT-I-004")>  _
    Partial Public Class DT_CONSULTA_DATOSTRABAJADORES_RES
        
        Private tI_ZTRABAJADORESField() As DT_CONSULTA_DATOSTRABAJADORES_RESTI_ZTRABAJADORES
        
        Private returnField As DT_CONSULTA_DATOSTRABAJADORES_RESReturn
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute("TI_ZTRABAJADORES", Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property TI_ZTRABAJADORES() As DT_CONSULTA_DATOSTRABAJADORES_RESTI_ZTRABAJADORES()
            Get
                Return Me.tI_ZTRABAJADORESField
            End Get
            Set
                Me.tI_ZTRABAJADORESField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property [return]() As DT_CONSULTA_DATOSTRABAJADORES_RESReturn
            Get
                Return Me.returnField
            End Get
            Set
                Me.returnField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute(AnonymousType:=true, [Namespace]:="https://www.ferreycorp.com.pe/HCM_LEGACY/ConsultaTrabajadores/HCM_PT-I-004")>  _
    Partial Public Class DT_CONSULTA_DATOSTRABAJADORES_RESTI_ZTRABAJADORES
        
        Private mandtField As String
        
        Private corporacionField As String
        
        Private sociedadField As String
        
        Private nombre_SociedadField As String
        
        Private codigoField As String
        
        Private nombre_CompletoField As String
        
        Private nombreField As String
        
        Private apellido_PaternoField As String
        
        Private apellido_MaternoField As String
        
        Private tipo_DocumentoField As String
        
        Private numero_DocumentoField As String
        
        Private sexoField As String
        
        Private estado_CivilField As String
        
        Private fecha_IngresoField As String
        
        Private unidad_OrganizatField As String
        
        Private desc_Unidad_OrgaField As String
        
        Private centro_CostoField As String
        
        Private desc_Centro_CostField As String
        
        Private division_PersonaField As String
        
        Private desc_Division_PeField As String
        
        Private subdivision_PersField As String
        
        Private desc_SubdivisionField As String
        
        Private posicionField As String
        
        Private desc_PosicionField As String
        
        Private area_PersonalField As String
        
        Private desc_Area_PersonField As String
        
        Private situacion_TrabajField As String
        
        Private fecha_NacimientoField As String
        
        Private fecha_CumpleanosField As String
        
        Private email_TrabajoField As String
        
        Private fecha_RetiroField As String
        
        Private codigo_JefeField As String
        
        Private nombre_JefeField As String
        
        Private areaFe_UnidadField As String
        
        Private areaFe_UnidesField As String
        
        Private areaFe_CodresField As String
        
        Private areaFe_DesresField As String
        
        Private subGer_UnidadField As String
        
        Private subGer_UnidesField As String
        
        Private subGer_CodresField As String
        
        Private subGer_DesresField As String
        
        Private gerenc_UnidadField As String
        
        Private gerenc_UnidesField As String
        
        Private gerenc_CodresField As String
        
        Private gerenc_DesresField As String
        
        Private gerDiv_UnidadField As String
        
        Private gerDiv_UnidesField As String
        
        Private gerDiv_CodresField As String
        
        Private gerDiv_DesresField As String
        
        Private gerCen_UnidadField As String
        
        Private gerCen_UnidesField As String
        
        Private gerCen_CodresField As String
        
        Private gerCen_DesresField As String
        
        Private gerGen_UnidadField As String
        
        Private gerGen_UnidesField As String
        
        Private gerGen_CodresField As String
        
        Private gerGen_DesresField As String
        
        Private gerCor_UnidadField As String
        
        Private gerCor_UnidesField As String
        
        Private gerCor_CodresField As String
        
        Private gerCor_DesresField As String
        
        Private gegCor_UnidadField As String
        
        Private gegCor_UnidesField As String
        
        Private gegCor_CodresField As String
        
        Private gegCor_DesresField As String
        
        Private precor_UnidadField As String
        
        Private precor_UnidesField As String
        
        Private precor_CodresField As String
        
        Private precor_DesresField As String
        
        Private codigo_AutogenerField As String
        
        Private lugar_ComercialField As String
        
        Private direcc_EstablecField As String
        
        Private ind_Meca_ViajeField As String
        
        Private cws_IDField As String
        
        Private cup_IDField As String
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property Mandt() As String
            Get
                Return Me.mandtField
            End Get
            Set
                Me.mandtField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property Corporacion() As String
            Get
                Return Me.corporacionField
            End Get
            Set
                Me.corporacionField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property Sociedad() As String
            Get
                Return Me.sociedadField
            End Get
            Set
                Me.sociedadField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property Nombre_Sociedad() As String
            Get
                Return Me.nombre_SociedadField
            End Get
            Set
                Me.nombre_SociedadField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property Codigo() As String
            Get
                Return Me.codigoField
            End Get
            Set
                Me.codigoField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property Nombre_Completo() As String
            Get
                Return Me.nombre_CompletoField
            End Get
            Set
                Me.nombre_CompletoField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property Nombre() As String
            Get
                Return Me.nombreField
            End Get
            Set
                Me.nombreField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property Apellido_Paterno() As String
            Get
                Return Me.apellido_PaternoField
            End Get
            Set
                Me.apellido_PaternoField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property Apellido_Materno() As String
            Get
                Return Me.apellido_MaternoField
            End Get
            Set
                Me.apellido_MaternoField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property Tipo_Documento() As String
            Get
                Return Me.tipo_DocumentoField
            End Get
            Set
                Me.tipo_DocumentoField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property Numero_Documento() As String
            Get
                Return Me.numero_DocumentoField
            End Get
            Set
                Me.numero_DocumentoField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property Sexo() As String
            Get
                Return Me.sexoField
            End Get
            Set
                Me.sexoField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property Estado_Civil() As String
            Get
                Return Me.estado_CivilField
            End Get
            Set
                Me.estado_CivilField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property Fecha_Ingreso() As String
            Get
                Return Me.fecha_IngresoField
            End Get
            Set
                Me.fecha_IngresoField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property Unidad_Organizat() As String
            Get
                Return Me.unidad_OrganizatField
            End Get
            Set
                Me.unidad_OrganizatField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property Desc_Unidad_Orga() As String
            Get
                Return Me.desc_Unidad_OrgaField
            End Get
            Set
                Me.desc_Unidad_OrgaField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property Centro_Costo() As String
            Get
                Return Me.centro_CostoField
            End Get
            Set
                Me.centro_CostoField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property Desc_Centro_Cost() As String
            Get
                Return Me.desc_Centro_CostField
            End Get
            Set
                Me.desc_Centro_CostField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property Division_Persona() As String
            Get
                Return Me.division_PersonaField
            End Get
            Set
                Me.division_PersonaField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property Desc_Division_Pe() As String
            Get
                Return Me.desc_Division_PeField
            End Get
            Set
                Me.desc_Division_PeField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property Subdivision_Pers() As String
            Get
                Return Me.subdivision_PersField
            End Get
            Set
                Me.subdivision_PersField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property Desc_Subdivision() As String
            Get
                Return Me.desc_SubdivisionField
            End Get
            Set
                Me.desc_SubdivisionField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property Posicion() As String
            Get
                Return Me.posicionField
            End Get
            Set
                Me.posicionField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property Desc_Posicion() As String
            Get
                Return Me.desc_PosicionField
            End Get
            Set
                Me.desc_PosicionField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property Area_Personal() As String
            Get
                Return Me.area_PersonalField
            End Get
            Set
                Me.area_PersonalField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property Desc_Area_Person() As String
            Get
                Return Me.desc_Area_PersonField
            End Get
            Set
                Me.desc_Area_PersonField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property Situacion_Trabaj() As String
            Get
                Return Me.situacion_TrabajField
            End Get
            Set
                Me.situacion_TrabajField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property Fecha_Nacimiento() As String
            Get
                Return Me.fecha_NacimientoField
            End Get
            Set
                Me.fecha_NacimientoField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property Fecha_Cumpleanos() As String
            Get
                Return Me.fecha_CumpleanosField
            End Get
            Set
                Me.fecha_CumpleanosField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property Email_Trabajo() As String
            Get
                Return Me.email_TrabajoField
            End Get
            Set
                Me.email_TrabajoField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property Fecha_Retiro() As String
            Get
                Return Me.fecha_RetiroField
            End Get
            Set
                Me.fecha_RetiroField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property Codigo_Jefe() As String
            Get
                Return Me.codigo_JefeField
            End Get
            Set
                Me.codigo_JefeField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property Nombre_Jefe() As String
            Get
                Return Me.nombre_JefeField
            End Get
            Set
                Me.nombre_JefeField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property AreaFe_Unidad() As String
            Get
                Return Me.areaFe_UnidadField
            End Get
            Set
                Me.areaFe_UnidadField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property AreaFe_Unides() As String
            Get
                Return Me.areaFe_UnidesField
            End Get
            Set
                Me.areaFe_UnidesField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property AreaFe_Codres() As String
            Get
                Return Me.areaFe_CodresField
            End Get
            Set
                Me.areaFe_CodresField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property AreaFe_Desres() As String
            Get
                Return Me.areaFe_DesresField
            End Get
            Set
                Me.areaFe_DesresField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property SubGer_Unidad() As String
            Get
                Return Me.subGer_UnidadField
            End Get
            Set
                Me.subGer_UnidadField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property SubGer_Unides() As String
            Get
                Return Me.subGer_UnidesField
            End Get
            Set
                Me.subGer_UnidesField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property SubGer_Codres() As String
            Get
                Return Me.subGer_CodresField
            End Get
            Set
                Me.subGer_CodresField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property SubGer_Desres() As String
            Get
                Return Me.subGer_DesresField
            End Get
            Set
                Me.subGer_DesresField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property Gerenc_Unidad() As String
            Get
                Return Me.gerenc_UnidadField
            End Get
            Set
                Me.gerenc_UnidadField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property Gerenc_Unides() As String
            Get
                Return Me.gerenc_UnidesField
            End Get
            Set
                Me.gerenc_UnidesField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property Gerenc_Codres() As String
            Get
                Return Me.gerenc_CodresField
            End Get
            Set
                Me.gerenc_CodresField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property Gerenc_Desres() As String
            Get
                Return Me.gerenc_DesresField
            End Get
            Set
                Me.gerenc_DesresField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property GerDiv_Unidad() As String
            Get
                Return Me.gerDiv_UnidadField
            End Get
            Set
                Me.gerDiv_UnidadField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property GerDiv_Unides() As String
            Get
                Return Me.gerDiv_UnidesField
            End Get
            Set
                Me.gerDiv_UnidesField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property GerDiv_Codres() As String
            Get
                Return Me.gerDiv_CodresField
            End Get
            Set
                Me.gerDiv_CodresField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property GerDiv_Desres() As String
            Get
                Return Me.gerDiv_DesresField
            End Get
            Set
                Me.gerDiv_DesresField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property GerCen_Unidad() As String
            Get
                Return Me.gerCen_UnidadField
            End Get
            Set
                Me.gerCen_UnidadField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property GerCen_Unides() As String
            Get
                Return Me.gerCen_UnidesField
            End Get
            Set
                Me.gerCen_UnidesField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property GerCen_Codres() As String
            Get
                Return Me.gerCen_CodresField
            End Get
            Set
                Me.gerCen_CodresField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property GerCen_Desres() As String
            Get
                Return Me.gerCen_DesresField
            End Get
            Set
                Me.gerCen_DesresField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property GerGen_Unidad() As String
            Get
                Return Me.gerGen_UnidadField
            End Get
            Set
                Me.gerGen_UnidadField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property GerGen_Unides() As String
            Get
                Return Me.gerGen_UnidesField
            End Get
            Set
                Me.gerGen_UnidesField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property GerGen_Codres() As String
            Get
                Return Me.gerGen_CodresField
            End Get
            Set
                Me.gerGen_CodresField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property GerGen_Desres() As String
            Get
                Return Me.gerGen_DesresField
            End Get
            Set
                Me.gerGen_DesresField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property GerCor_Unidad() As String
            Get
                Return Me.gerCor_UnidadField
            End Get
            Set
                Me.gerCor_UnidadField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property GerCor_Unides() As String
            Get
                Return Me.gerCor_UnidesField
            End Get
            Set
                Me.gerCor_UnidesField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property GerCor_Codres() As String
            Get
                Return Me.gerCor_CodresField
            End Get
            Set
                Me.gerCor_CodresField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property GerCor_Desres() As String
            Get
                Return Me.gerCor_DesresField
            End Get
            Set
                Me.gerCor_DesresField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property GegCor_Unidad() As String
            Get
                Return Me.gegCor_UnidadField
            End Get
            Set
                Me.gegCor_UnidadField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property GegCor_Unides() As String
            Get
                Return Me.gegCor_UnidesField
            End Get
            Set
                Me.gegCor_UnidesField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property GegCor_Codres() As String
            Get
                Return Me.gegCor_CodresField
            End Get
            Set
                Me.gegCor_CodresField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property GegCor_Desres() As String
            Get
                Return Me.gegCor_DesresField
            End Get
            Set
                Me.gegCor_DesresField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property Precor_Unidad() As String
            Get
                Return Me.precor_UnidadField
            End Get
            Set
                Me.precor_UnidadField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property Precor_Unides() As String
            Get
                Return Me.precor_UnidesField
            End Get
            Set
                Me.precor_UnidesField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property Precor_Codres() As String
            Get
                Return Me.precor_CodresField
            End Get
            Set
                Me.precor_CodresField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property Precor_Desres() As String
            Get
                Return Me.precor_DesresField
            End Get
            Set
                Me.precor_DesresField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property Codigo_Autogener() As String
            Get
                Return Me.codigo_AutogenerField
            End Get
            Set
                Me.codigo_AutogenerField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property Lugar_Comercial() As String
            Get
                Return Me.lugar_ComercialField
            End Get
            Set
                Me.lugar_ComercialField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property Direcc_Establec() As String
            Get
                Return Me.direcc_EstablecField
            End Get
            Set
                Me.direcc_EstablecField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property Ind_Meca_Viaje() As String
            Get
                Return Me.ind_Meca_ViajeField
            End Get
            Set
                Me.ind_Meca_ViajeField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property Cws_ID() As String
            Get
                Return Me.cws_IDField
            End Get
            Set
                Me.cws_IDField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property Cup_ID() As String
            Get
                Return Me.cup_IDField
            End Get
            Set
                Me.cup_IDField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute(AnonymousType:=true, [Namespace]:="https://www.ferreycorp.com.pe/HCM_LEGACY/ConsultaTrabajadores/HCM_PT-I-004")>  _
    Partial Public Class DT_CONSULTA_DATOSTRABAJADORES_RESReturn
        
        Private messageField As String
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property message() As String
            Get
                Return Me.messageField
            End Get
            Set
                Me.messageField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")>  _
    Public Delegate Sub SI_OS_CONSULTA_DATOS_TRABAJADORESCompletedEventHandler(ByVal sender As Object, ByVal e As SI_OS_CONSULTA_DATOS_TRABAJADORESCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class SI_OS_CONSULTA_DATOS_TRABAJADORESCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As DT_CONSULTA_DATOSTRABAJADORES_RES
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),DT_CONSULTA_DATOSTRABAJADORES_RES)
            End Get
        End Property
    End Class
End Namespace
