'------------------------------------------------------------------------------
' <auto-generated>
'     Este código fue generado por una herramienta.
'     Versión de runtime:4.0.30319.42000
'
'     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
'     se vuelve a generar el código.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On

Imports System
Imports System.ComponentModel
Imports System.Diagnostics
Imports System.Web.Services
Imports System.Web.Services.Protocols
Imports System.Xml.Serialization

'
'Microsoft.VSDesigner generó automáticamente este código fuente, versión=4.0.30319.42000.
'
Namespace wsHanaUnidadesOrganizativas
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3062.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Web.Services.WebServiceBindingAttribute(Name:="SI_OS_CONSULTA_UNIDAD_ORGANIZATIVABinding", [Namespace]:="https://www.ferreycorp.com.pe/HCM_LEGACY/ConsultaTrabajadores/HCM_PT-I-004")>  _
    Partial Public Class SI_OS_CONSULTA_UNIDAD_ORGANIZATIVAService
        Inherits System.Web.Services.Protocols.SoapHttpClientProtocol
        
        Private SI_OS_CONSULTA_UNIDAD_ORGANIZATIVAOperationCompleted As System.Threading.SendOrPostCallback
        
        Private useDefaultCredentialsSetExplicitly As Boolean
        
        '''<remarks/>
        Public Sub New()
            MyBase.New
            Me.Url = Global.ServicioExterno.My.MySettings.Default.ServicioExterno_wsUnidadesOrganizativas_SI_OS_CONSULTA_UNIDAD_ORGANIZATIVAService
            If (Me.IsLocalFileSystemWebService(Me.Url) = true) Then
                Me.UseDefaultCredentials = true
                Me.useDefaultCredentialsSetExplicitly = false
            Else
                Me.useDefaultCredentialsSetExplicitly = true
            End If
        End Sub
        
        Public Shadows Property Url() As String
            Get
                Return MyBase.Url
            End Get
            Set
                If (((Me.IsLocalFileSystemWebService(MyBase.Url) = true)  _
                            AndAlso (Me.useDefaultCredentialsSetExplicitly = false))  _
                            AndAlso (Me.IsLocalFileSystemWebService(value) = false)) Then
                    MyBase.UseDefaultCredentials = false
                End If
                MyBase.Url = value
            End Set
        End Property
        
        Public Shadows Property UseDefaultCredentials() As Boolean
            Get
                Return MyBase.UseDefaultCredentials
            End Get
            Set
                MyBase.UseDefaultCredentials = value
                Me.useDefaultCredentialsSetExplicitly = true
            End Set
        End Property
        
        '''<remarks/>
        Public Event SI_OS_CONSULTA_UNIDAD_ORGANIZATIVACompleted As SI_OS_CONSULTA_UNIDAD_ORGANIZATIVACompletedEventHandler
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://sap.com/xi/WebService/soap1.1", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Bare)>  _
        Public Function SI_OS_CONSULTA_UNIDAD_ORGANIZATIVA(<System.Xml.Serialization.XmlElementAttribute([Namespace]:="https://www.ferreycorp.com.pe/HCM_LEGACY/ConsultaTrabajadores/HCM_PT-I-004")> ByVal MT_CONSULTA_UNIDAD_ORGANIZATIVA_REQ As DT_CONSULTA_UNIDAD_ORGANIZATIVA_REQ) As <System.Xml.Serialization.XmlArrayAttribute("MT_CONSULTA_UNIDAD_ORGANIZATIVA_RES", [Namespace]:="https://www.ferreycorp.com.pe/HCM_LEGACY/ConsultaTrabajadores/HCM_PT-I-004"), System.Xml.Serialization.XmlArrayItemAttribute("IT_ZUND_ORGANIZATIV", Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable:=false)> DT_CONSULTA_UNIDAD_ORGANIZATIVA_RESIT_ZUND_ORGANIZATIV()
            Dim results() As Object = Me.Invoke("SI_OS_CONSULTA_UNIDAD_ORGANIZATIVA", New Object() {MT_CONSULTA_UNIDAD_ORGANIZATIVA_REQ})
            Return CType(results(0),DT_CONSULTA_UNIDAD_ORGANIZATIVA_RESIT_ZUND_ORGANIZATIV())
        End Function
        
        '''<remarks/>
        Public Overloads Sub SI_OS_CONSULTA_UNIDAD_ORGANIZATIVAAsync(ByVal MT_CONSULTA_UNIDAD_ORGANIZATIVA_REQ As DT_CONSULTA_UNIDAD_ORGANIZATIVA_REQ)
            Me.SI_OS_CONSULTA_UNIDAD_ORGANIZATIVAAsync(MT_CONSULTA_UNIDAD_ORGANIZATIVA_REQ, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub SI_OS_CONSULTA_UNIDAD_ORGANIZATIVAAsync(ByVal MT_CONSULTA_UNIDAD_ORGANIZATIVA_REQ As DT_CONSULTA_UNIDAD_ORGANIZATIVA_REQ, ByVal userState As Object)
            If (Me.SI_OS_CONSULTA_UNIDAD_ORGANIZATIVAOperationCompleted Is Nothing) Then
                Me.SI_OS_CONSULTA_UNIDAD_ORGANIZATIVAOperationCompleted = AddressOf Me.OnSI_OS_CONSULTA_UNIDAD_ORGANIZATIVAOperationCompleted
            End If
            Me.InvokeAsync("SI_OS_CONSULTA_UNIDAD_ORGANIZATIVA", New Object() {MT_CONSULTA_UNIDAD_ORGANIZATIVA_REQ}, Me.SI_OS_CONSULTA_UNIDAD_ORGANIZATIVAOperationCompleted, userState)
        End Sub
        
        Private Sub OnSI_OS_CONSULTA_UNIDAD_ORGANIZATIVAOperationCompleted(ByVal arg As Object)
            If (Not (Me.SI_OS_CONSULTA_UNIDAD_ORGANIZATIVACompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent SI_OS_CONSULTA_UNIDAD_ORGANIZATIVACompleted(Me, New SI_OS_CONSULTA_UNIDAD_ORGANIZATIVACompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        Public Shadows Sub CancelAsync(ByVal userState As Object)
            MyBase.CancelAsync(userState)
        End Sub
        
        Private Function IsLocalFileSystemWebService(ByVal url As String) As Boolean
            If ((url Is Nothing)  _
                        OrElse (url Is String.Empty)) Then
                Return false
            End If
            Dim wsUri As System.Uri = New System.Uri(url)
            If ((wsUri.Port >= 1024)  _
                        AndAlso (String.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) = 0)) Then
                Return true
            End If
            Return false
        End Function
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3221.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="https://www.ferreycorp.com.pe/HCM_LEGACY/ConsultaTrabajadores/HCM_PT-I-004")>  _
    Partial Public Class DT_CONSULTA_UNIDAD_ORGANIZATIVA_REQ
        
        Private unidad_OrgaField As String
        
        Private sociedadField As String
        
        Private unidad_OrgSupField As String
        
        Private desc_UnidadOrgaField As String
        
        Private codigo_ResponsableField As String
        
        Private sit_FuncField As String
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property Unidad_Orga() As String
            Get
                Return Me.unidad_OrgaField
            End Get
            Set
                Me.unidad_OrgaField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property Sociedad() As String
            Get
                Return Me.sociedadField
            End Get
            Set
                Me.sociedadField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property Unidad_OrgSup() As String
            Get
                Return Me.unidad_OrgSupField
            End Get
            Set
                Me.unidad_OrgSupField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property Desc_UnidadOrga() As String
            Get
                Return Me.desc_UnidadOrgaField
            End Get
            Set
                Me.desc_UnidadOrgaField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property Codigo_Responsable() As String
            Get
                Return Me.codigo_ResponsableField
            End Get
            Set
                Me.codigo_ResponsableField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property Sit_Func() As String
            Get
                Return Me.sit_FuncField
            End Get
            Set
                Me.sit_FuncField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3221.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute(AnonymousType:=true, [Namespace]:="https://www.ferreycorp.com.pe/HCM_LEGACY/ConsultaTrabajadores/HCM_PT-I-004")>  _
    Partial Public Class DT_CONSULTA_UNIDAD_ORGANIZATIVA_RESIT_ZUND_ORGANIZATIV
        
        Private corporacionField As String
        
        Private sociedadField As String
        
        Private unidad_OrgaField As String
        
        Private unid_Organiz_SupField As String
        
        Private desc_Unidad_OrgaField As String
        
        Private codigo_ResponsableField As String
        
        Private funcionesField As String
        
        Private sit_Unid_FuncField As String
        
        Private nivelField As String
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property Corporacion() As String
            Get
                Return Me.corporacionField
            End Get
            Set
                Me.corporacionField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property Sociedad() As String
            Get
                Return Me.sociedadField
            End Get
            Set
                Me.sociedadField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property Unidad_Orga() As String
            Get
                Return Me.unidad_OrgaField
            End Get
            Set
                Me.unidad_OrgaField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property Unid_Organiz_Sup() As String
            Get
                Return Me.unid_Organiz_SupField
            End Get
            Set
                Me.unid_Organiz_SupField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property Desc_Unidad_Orga() As String
            Get
                Return Me.desc_Unidad_OrgaField
            End Get
            Set
                Me.desc_Unidad_OrgaField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property Codigo_Responsable() As String
            Get
                Return Me.codigo_ResponsableField
            End Get
            Set
                Me.codigo_ResponsableField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property Funciones() As String
            Get
                Return Me.funcionesField
            End Get
            Set
                Me.funcionesField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property Sit_Unid_Func() As String
            Get
                Return Me.sit_Unid_FuncField
            End Get
            Set
                Me.sit_Unid_FuncField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property Nivel() As String
            Get
                Return Me.nivelField
            End Get
            Set
                Me.nivelField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3062.0")>  _
    Public Delegate Sub SI_OS_CONSULTA_UNIDAD_ORGANIZATIVACompletedEventHandler(ByVal sender As Object, ByVal e As SI_OS_CONSULTA_UNIDAD_ORGANIZATIVACompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3062.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class SI_OS_CONSULTA_UNIDAD_ORGANIZATIVACompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As DT_CONSULTA_UNIDAD_ORGANIZATIVA_RESIT_ZUND_ORGANIZATIV()
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),DT_CONSULTA_UNIDAD_ORGANIZATIVA_RESIT_ZUND_ORGANIZATIV())
            End Get
        End Property
    End Class
End Namespace
