'------------------------------------------------------------------------------
' <auto-generated>
'     Este código fue generado por una herramienta.
'     Versión de runtime:4.0.30319.42000
'
'     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
'     se vuelve a generar el código.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On

Imports System
Imports System.ComponentModel
Imports System.Diagnostics
Imports System.Web.Services
Imports System.Web.Services.Protocols
Imports System.Xml.Serialization

'
'Microsoft.VSDesigner generó automáticamente este código fuente, versión=4.0.30319.42000.
'
Namespace EccService
    
    'CODEGEN: No se controló el elemento de extensión WSDL opcional 'Policy' del espacio de nombres 'http://schemas.xmlsoap.org/ws/2004/09/policy'.
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Web.Services.WebServiceBindingAttribute(Name:="SERVICETRABAJADOR", [Namespace]:="urn:sap-com:document:sap:soap:functions:mc-style")>  _
    Partial Public Class SERVICETRABAJADOR
        Inherits System.Web.Services.Protocols.SoapHttpClientProtocol
        
        Private ConsultarUnidorgOperationCompleted As System.Threading.SendOrPostCallback
        
        Private ValidaTrabOperationCompleted As System.Threading.SendOrPostCallback
        
        Private ZfmhrConsultaJornalPeOperationCompleted As System.Threading.SendOrPostCallback
        
        Private ConsultaTrabOperationCompleted As System.Threading.SendOrPostCallback
        
        Private useDefaultCredentialsSetExplicitly As Boolean
        
        '''<remarks/>
        Public Sub New()
            MyBase.New
            Me.Url = Global.ServicioExterno.My.MySettings.Default.ServicioExterno_EccService_SERVICETRABAJADOR
            If (Me.IsLocalFileSystemWebService(Me.Url) = true) Then
                Me.UseDefaultCredentials = true
                Me.useDefaultCredentialsSetExplicitly = false
            Else
                Me.useDefaultCredentialsSetExplicitly = true
            End If
        End Sub
        
        Public Shadows Property Url() As String
            Get
                Return MyBase.Url
            End Get
            Set
                If (((Me.IsLocalFileSystemWebService(MyBase.Url) = true)  _
                            AndAlso (Me.useDefaultCredentialsSetExplicitly = false))  _
                            AndAlso (Me.IsLocalFileSystemWebService(value) = false)) Then
                    MyBase.UseDefaultCredentials = false
                End If
                MyBase.Url = value
            End Set
        End Property
        
        Public Shadows Property UseDefaultCredentials() As Boolean
            Get
                Return MyBase.UseDefaultCredentials
            End Get
            Set
                MyBase.UseDefaultCredentials = value
                Me.useDefaultCredentialsSetExplicitly = true
            End Set
        End Property
        
        '''<remarks/>
        Public Event ConsultarUnidorgCompleted As ConsultarUnidorgCompletedEventHandler
        
        '''<remarks/>
        Public Event ValidaTrabCompleted As ValidaTrabCompletedEventHandler
        
        '''<remarks/>
        Public Event ZfmhrConsultaJornalPeCompleted As ZfmhrConsultaJornalPeCompletedEventHandler
        
        '''<remarks/>
        Public Event ConsultaTrabCompleted As ConsultaTrabCompletedEventHandler
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:sap-com:document:sap:soap:functions:mc-style:ZWSHR_TRABAJADOR_PE:ConsultarUni"& _ 
            "dorgRequest", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Bare)>  _
        Public Function ConsultarUnidorg(<System.Xml.Serialization.XmlElementAttribute("ConsultarUnidorg", [Namespace]:="urn:sap-com:document:sap:soap:functions:mc-style")> ByVal ConsultarUnidorg1 As ConsultarUnidorg) As <System.Xml.Serialization.XmlElementAttribute("ConsultarUnidorgResponse", [Namespace]:="urn:sap-com:document:sap:soap:functions:mc-style")> ConsultarUnidorgResponse
            Dim results() As Object = Me.Invoke("ConsultarUnidorg", New Object() {ConsultarUnidorg1})
            Return CType(results(0),ConsultarUnidorgResponse)
        End Function
        
        '''<remarks/>
        Public Overloads Sub ConsultarUnidorgAsync(ByVal ConsultarUnidorg1 As ConsultarUnidorg)
            Me.ConsultarUnidorgAsync(ConsultarUnidorg1, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub ConsultarUnidorgAsync(ByVal ConsultarUnidorg1 As ConsultarUnidorg, ByVal userState As Object)
            If (Me.ConsultarUnidorgOperationCompleted Is Nothing) Then
                Me.ConsultarUnidorgOperationCompleted = AddressOf Me.OnConsultarUnidorgOperationCompleted
            End If
            Me.InvokeAsync("ConsultarUnidorg", New Object() {ConsultarUnidorg1}, Me.ConsultarUnidorgOperationCompleted, userState)
        End Sub
        
        Private Sub OnConsultarUnidorgOperationCompleted(ByVal arg As Object)
            If (Not (Me.ConsultarUnidorgCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent ConsultarUnidorgCompleted(Me, New ConsultarUnidorgCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:sap-com:document:sap:soap:functions:mc-style:ZWSHR_TRABAJADOR_PE:ValidaTrabRe"& _ 
            "quest", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Bare)>  _
        Public Function ValidaTrab(<System.Xml.Serialization.XmlElementAttribute("ValidaTrab", [Namespace]:="urn:sap-com:document:sap:soap:functions:mc-style")> ByVal ValidaTrab1 As ValidaTrab) As <System.Xml.Serialization.XmlElementAttribute("ValidaTrabResponse", [Namespace]:="urn:sap-com:document:sap:soap:functions:mc-style")> ValidaTrabResponse
            Dim results() As Object = Me.Invoke("ValidaTrab", New Object() {ValidaTrab1})
            Return CType(results(0),ValidaTrabResponse)
        End Function
        
        '''<remarks/>
        Public Overloads Sub ValidaTrabAsync(ByVal ValidaTrab1 As ValidaTrab)
            Me.ValidaTrabAsync(ValidaTrab1, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub ValidaTrabAsync(ByVal ValidaTrab1 As ValidaTrab, ByVal userState As Object)
            If (Me.ValidaTrabOperationCompleted Is Nothing) Then
                Me.ValidaTrabOperationCompleted = AddressOf Me.OnValidaTrabOperationCompleted
            End If
            Me.InvokeAsync("ValidaTrab", New Object() {ValidaTrab1}, Me.ValidaTrabOperationCompleted, userState)
        End Sub
        
        Private Sub OnValidaTrabOperationCompleted(ByVal arg As Object)
            If (Not (Me.ValidaTrabCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent ValidaTrabCompleted(Me, New ValidaTrabCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:sap-com:document:sap:soap:functions:mc-style:ZWSHR_TRABAJADOR_PE:ZfmhrConsult"& _ 
            "aJornalPeRequest", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Bare)>  _
        Public Function ZfmhrConsultaJornalPe(<System.Xml.Serialization.XmlElementAttribute("ZfmhrConsultaJornalPe", [Namespace]:="urn:sap-com:document:sap:soap:functions:mc-style")> ByVal ZfmhrConsultaJornalPe1 As ZfmhrConsultaJornalPe) As <System.Xml.Serialization.XmlElementAttribute("ZfmhrConsultaJornalPeResponse", [Namespace]:="urn:sap-com:document:sap:soap:functions:mc-style")> ZfmhrConsultaJornalPeResponse
            Dim results() As Object = Me.Invoke("ZfmhrConsultaJornalPe", New Object() {ZfmhrConsultaJornalPe1})
            Return CType(results(0),ZfmhrConsultaJornalPeResponse)
        End Function
        
        '''<remarks/>
        Public Overloads Sub ZfmhrConsultaJornalPeAsync(ByVal ZfmhrConsultaJornalPe1 As ZfmhrConsultaJornalPe)
            Me.ZfmhrConsultaJornalPeAsync(ZfmhrConsultaJornalPe1, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub ZfmhrConsultaJornalPeAsync(ByVal ZfmhrConsultaJornalPe1 As ZfmhrConsultaJornalPe, ByVal userState As Object)
            If (Me.ZfmhrConsultaJornalPeOperationCompleted Is Nothing) Then
                Me.ZfmhrConsultaJornalPeOperationCompleted = AddressOf Me.OnZfmhrConsultaJornalPeOperationCompleted
            End If
            Me.InvokeAsync("ZfmhrConsultaJornalPe", New Object() {ZfmhrConsultaJornalPe1}, Me.ZfmhrConsultaJornalPeOperationCompleted, userState)
        End Sub
        
        Private Sub OnZfmhrConsultaJornalPeOperationCompleted(ByVal arg As Object)
            If (Not (Me.ZfmhrConsultaJornalPeCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent ZfmhrConsultaJornalPeCompleted(Me, New ZfmhrConsultaJornalPeCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:sap-com:document:sap:soap:functions:mc-style:ZWSHR_TRABAJADOR_PE:ConsultaTrab"& _ 
            "Request", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Bare)>  _
        Public Function ConsultaTrab(<System.Xml.Serialization.XmlElementAttribute("ConsultaTrab", [Namespace]:="urn:sap-com:document:sap:soap:functions:mc-style")> ByVal ConsultaTrab1 As ConsultaTrab) As <System.Xml.Serialization.XmlElementAttribute("ConsultaTrabResponse", [Namespace]:="urn:sap-com:document:sap:soap:functions:mc-style")> ConsultaTrabResponse
            Dim results() As Object = Me.Invoke("ConsultaTrab", New Object() {ConsultaTrab1})
            Return CType(results(0),ConsultaTrabResponse)
        End Function
        
        '''<remarks/>
        Public Overloads Sub ConsultaTrabAsync(ByVal ConsultaTrab1 As ConsultaTrab)
            Me.ConsultaTrabAsync(ConsultaTrab1, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub ConsultaTrabAsync(ByVal ConsultaTrab1 As ConsultaTrab, ByVal userState As Object)
            If (Me.ConsultaTrabOperationCompleted Is Nothing) Then
                Me.ConsultaTrabOperationCompleted = AddressOf Me.OnConsultaTrabOperationCompleted
            End If
            Me.InvokeAsync("ConsultaTrab", New Object() {ConsultaTrab1}, Me.ConsultaTrabOperationCompleted, userState)
        End Sub
        
        Private Sub OnConsultaTrabOperationCompleted(ByVal arg As Object)
            If (Not (Me.ConsultaTrabCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent ConsultaTrabCompleted(Me, New ConsultaTrabCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        Public Shadows Sub CancelAsync(ByVal userState As Object)
            MyBase.CancelAsync(userState)
        End Sub
        
        Private Function IsLocalFileSystemWebService(ByVal url As String) As Boolean
            If ((url Is Nothing)  _
                        OrElse (url Is String.Empty)) Then
                Return false
            End If
            Dim wsUri As System.Uri = New System.Uri(url)
            If ((wsUri.Port >= 1024)  _
                        AndAlso (String.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) = 0)) Then
                Return true
            End If
            Return false
        End Function
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute(AnonymousType:=true, [Namespace]:="urn:sap-com:document:sap:soap:functions:mc-style")>  _
    Partial Public Class ConsultarUnidorg
        
        Private desUnidadOrgField As String
        
        Private responsableField As String
        
        Private situacion_FuncionesField As String
        
        Private sociedadField As String
        
        Private tUnidadOrgField() As ZundOrganizativ
        
        Private unidadOrgField As String
        
        Private unidadOrgSupField As String
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property DesUnidadOrg() As String
            Get
                Return Me.desUnidadOrgField
            End Get
            Set
                Me.desUnidadOrgField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property Responsable() As String
            Get
                Return Me.responsableField
            End Get
            Set
                Me.responsableField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property Situacion_Funciones() As String
            Get
                Return Me.situacion_FuncionesField
            End Get
            Set
                Me.situacion_FuncionesField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property Sociedad() As String
            Get
                Return Me.sociedadField
            End Get
            Set
                Me.sociedadField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlArrayAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified),  _
         System.Xml.Serialization.XmlArrayItemAttribute("item", Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable:=false)>  _
        Public Property TUnidadOrg() As ZundOrganizativ()
            Get
                Return Me.tUnidadOrgField
            End Get
            Set
                Me.tUnidadOrgField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property UnidadOrg() As String
            Get
                Return Me.unidadOrgField
            End Get
            Set
                Me.unidadOrgField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property UnidadOrgSup() As String
            Get
                Return Me.unidadOrgSupField
            End Get
            Set
                Me.unidadOrgSupField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="urn:sap-com:document:sap:soap:functions:mc-style")>  _
    Partial Public Class ZundOrganizativ
        
        Private mandtField As String
        
        Private corporacionField As String
        
        Private sociedadField As String
        
        Private unidadOrganizatField As String
        
        Private unidOrganizSupField As String
        
        Private descUnidadOrgaField As String
        
        Private codigoResponsabField As String
        
        Private funcionesField As String
        
        Private sitUnidFuncField As String
        
        Private nivelField As String
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property Mandt() As String
            Get
                Return Me.mandtField
            End Get
            Set
                Me.mandtField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property Corporacion() As String
            Get
                Return Me.corporacionField
            End Get
            Set
                Me.corporacionField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property Sociedad() As String
            Get
                Return Me.sociedadField
            End Get
            Set
                Me.sociedadField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property UnidadOrganizat() As String
            Get
                Return Me.unidadOrganizatField
            End Get
            Set
                Me.unidadOrganizatField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property UnidOrganizSup() As String
            Get
                Return Me.unidOrganizSupField
            End Get
            Set
                Me.unidOrganizSupField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property DescUnidadOrga() As String
            Get
                Return Me.descUnidadOrgaField
            End Get
            Set
                Me.descUnidadOrgaField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property CodigoResponsab() As String
            Get
                Return Me.codigoResponsabField
            End Get
            Set
                Me.codigoResponsabField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property Funciones() As String
            Get
                Return Me.funcionesField
            End Get
            Set
                Me.funcionesField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property SitUnidFunc() As String
            Get
                Return Me.sitUnidFuncField
            End Get
            Set
                Me.sitUnidFuncField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property Nivel() As String
            Get
                Return Me.nivelField
            End Get
            Set
                Me.nivelField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="urn:sap-com:document:sap:soap:functions:mc-style")>  _
    Partial Public Class Ztrabajadores
        
        Private mandtField As String
        
        Private corporacionField As String
        
        Private sociedadField As String
        
        Private nombreSociedadField As String
        
        Private codigoField As String
        
        Private nombreCompletoField As String
        
        Private nombreField As String
        
        Private apellidoPaternoField As String
        
        Private apellidoMaternoField As String
        
        Private tipoDocumentoField As String
        
        Private numeroDocumentoField As String
        
        Private sexoField As String
        
        Private estadoCivilField As String
        
        Private fechaIngresoField As String
        
        Private unidadOrganizatField As String
        
        Private descUnidadOrgaField As String
        
        Private centroCostoField As String
        
        Private descCentroCostField As String
        
        Private divisionPersonaField As String
        
        Private descDivisionPeField As String
        
        Private subdivisionPersField As String
        
        Private descSubdivisionField As String
        
        Private posicionField As String
        
        Private descPosicionField As String
        
        Private areaPersonalField As String
        
        Private descAreaPersonField As String
        
        Private situacionTrabajField As String
        
        Private fechaNacimientoField As String
        
        Private fechaCumpleanosField As String
        
        Private emailTrabajoField As String
        
        Private fechaRetiroField As String
        
        Private codigoJefeField As String
        
        Private nombreJefeField As String
        
        Private areafeUnidadField As String
        
        Private areafeUnidesField As String
        
        Private areafeCodresField As String
        
        Private areafeDesresField As String
        
        Private subgerUnidadField As String
        
        Private subgerUnidesField As String
        
        Private subgerCodresField As String
        
        Private subgerDesresField As String
        
        Private gerencUnidadField As String
        
        Private gerencUnidesField As String
        
        Private gerencCodresField As String
        
        Private gerencDesresField As String
        
        Private gerdivUnidadField As String
        
        Private gerdivUnidesField As String
        
        Private gerdivCodresField As String
        
        Private gerdivDesresField As String
        
        Private gercenUnidadField As String
        
        Private gercenUnidesField As String
        
        Private gercenCodresField As String
        
        Private gercenDesresField As String
        
        Private gergenUnidadField As String
        
        Private gergenUnidesField As String
        
        Private gergenCodresField As String
        
        Private gergenDesresField As String
        
        Private gercorUnidadField As String
        
        Private gercorUnidesField As String
        
        Private gercorCodresField As String
        
        Private gercorDesresField As String
        
        Private gegcorUnidadField As String
        
        Private gegcorUnidesField As String
        
        Private gegcorCodresField As String
        
        Private gegcorDesresField As String
        
        Private precorUnidadField As String
        
        Private precorUnidesField As String
        
        Private precorCodresField As String
        
        Private precorDesresField As String
        
        Private codigoAutogenerField As String
        
        Private lugarComercialField As String
        
        Private direccEstablecField As String
        
        Private indMecaViajeField As String
        
        Private cwsIdField As String
        
        Private cupIdField As String
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property Mandt() As String
            Get
                Return Me.mandtField
            End Get
            Set
                Me.mandtField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property Corporacion() As String
            Get
                Return Me.corporacionField
            End Get
            Set
                Me.corporacionField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property Sociedad() As String
            Get
                Return Me.sociedadField
            End Get
            Set
                Me.sociedadField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property NombreSociedad() As String
            Get
                Return Me.nombreSociedadField
            End Get
            Set
                Me.nombreSociedadField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property Codigo() As String
            Get
                Return Me.codigoField
            End Get
            Set
                Me.codigoField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property NombreCompleto() As String
            Get
                Return Me.nombreCompletoField
            End Get
            Set
                Me.nombreCompletoField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property Nombre() As String
            Get
                Return Me.nombreField
            End Get
            Set
                Me.nombreField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property ApellidoPaterno() As String
            Get
                Return Me.apellidoPaternoField
            End Get
            Set
                Me.apellidoPaternoField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property ApellidoMaterno() As String
            Get
                Return Me.apellidoMaternoField
            End Get
            Set
                Me.apellidoMaternoField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property TipoDocumento() As String
            Get
                Return Me.tipoDocumentoField
            End Get
            Set
                Me.tipoDocumentoField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property NumeroDocumento() As String
            Get
                Return Me.numeroDocumentoField
            End Get
            Set
                Me.numeroDocumentoField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property Sexo() As String
            Get
                Return Me.sexoField
            End Get
            Set
                Me.sexoField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property EstadoCivil() As String
            Get
                Return Me.estadoCivilField
            End Get
            Set
                Me.estadoCivilField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property FechaIngreso() As String
            Get
                Return Me.fechaIngresoField
            End Get
            Set
                Me.fechaIngresoField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property UnidadOrganizat() As String
            Get
                Return Me.unidadOrganizatField
            End Get
            Set
                Me.unidadOrganizatField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property DescUnidadOrga() As String
            Get
                Return Me.descUnidadOrgaField
            End Get
            Set
                Me.descUnidadOrgaField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property CentroCosto() As String
            Get
                Return Me.centroCostoField
            End Get
            Set
                Me.centroCostoField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property DescCentroCost() As String
            Get
                Return Me.descCentroCostField
            End Get
            Set
                Me.descCentroCostField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property DivisionPersona() As String
            Get
                Return Me.divisionPersonaField
            End Get
            Set
                Me.divisionPersonaField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property DescDivisionPe() As String
            Get
                Return Me.descDivisionPeField
            End Get
            Set
                Me.descDivisionPeField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property SubdivisionPers() As String
            Get
                Return Me.subdivisionPersField
            End Get
            Set
                Me.subdivisionPersField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property DescSubdivision() As String
            Get
                Return Me.descSubdivisionField
            End Get
            Set
                Me.descSubdivisionField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property Posicion() As String
            Get
                Return Me.posicionField
            End Get
            Set
                Me.posicionField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property DescPosicion() As String
            Get
                Return Me.descPosicionField
            End Get
            Set
                Me.descPosicionField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property AreaPersonal() As String
            Get
                Return Me.areaPersonalField
            End Get
            Set
                Me.areaPersonalField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property DescAreaPerson() As String
            Get
                Return Me.descAreaPersonField
            End Get
            Set
                Me.descAreaPersonField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property SituacionTrabaj() As String
            Get
                Return Me.situacionTrabajField
            End Get
            Set
                Me.situacionTrabajField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property FechaNacimiento() As String
            Get
                Return Me.fechaNacimientoField
            End Get
            Set
                Me.fechaNacimientoField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property FechaCumpleanos() As String
            Get
                Return Me.fechaCumpleanosField
            End Get
            Set
                Me.fechaCumpleanosField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property EmailTrabajo() As String
            Get
                Return Me.emailTrabajoField
            End Get
            Set
                Me.emailTrabajoField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property FechaRetiro() As String
            Get
                Return Me.fechaRetiroField
            End Get
            Set
                Me.fechaRetiroField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property CodigoJefe() As String
            Get
                Return Me.codigoJefeField
            End Get
            Set
                Me.codigoJefeField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property NombreJefe() As String
            Get
                Return Me.nombreJefeField
            End Get
            Set
                Me.nombreJefeField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property AreafeUnidad() As String
            Get
                Return Me.areafeUnidadField
            End Get
            Set
                Me.areafeUnidadField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property AreafeUnides() As String
            Get
                Return Me.areafeUnidesField
            End Get
            Set
                Me.areafeUnidesField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property AreafeCodres() As String
            Get
                Return Me.areafeCodresField
            End Get
            Set
                Me.areafeCodresField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property AreafeDesres() As String
            Get
                Return Me.areafeDesresField
            End Get
            Set
                Me.areafeDesresField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property SubgerUnidad() As String
            Get
                Return Me.subgerUnidadField
            End Get
            Set
                Me.subgerUnidadField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property SubgerUnides() As String
            Get
                Return Me.subgerUnidesField
            End Get
            Set
                Me.subgerUnidesField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property SubgerCodres() As String
            Get
                Return Me.subgerCodresField
            End Get
            Set
                Me.subgerCodresField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property SubgerDesres() As String
            Get
                Return Me.subgerDesresField
            End Get
            Set
                Me.subgerDesresField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property GerencUnidad() As String
            Get
                Return Me.gerencUnidadField
            End Get
            Set
                Me.gerencUnidadField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property GerencUnides() As String
            Get
                Return Me.gerencUnidesField
            End Get
            Set
                Me.gerencUnidesField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property GerencCodres() As String
            Get
                Return Me.gerencCodresField
            End Get
            Set
                Me.gerencCodresField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property GerencDesres() As String
            Get
                Return Me.gerencDesresField
            End Get
            Set
                Me.gerencDesresField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property GerdivUnidad() As String
            Get
                Return Me.gerdivUnidadField
            End Get
            Set
                Me.gerdivUnidadField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property GerdivUnides() As String
            Get
                Return Me.gerdivUnidesField
            End Get
            Set
                Me.gerdivUnidesField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property GerdivCodres() As String
            Get
                Return Me.gerdivCodresField
            End Get
            Set
                Me.gerdivCodresField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property GerdivDesres() As String
            Get
                Return Me.gerdivDesresField
            End Get
            Set
                Me.gerdivDesresField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property GercenUnidad() As String
            Get
                Return Me.gercenUnidadField
            End Get
            Set
                Me.gercenUnidadField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property GercenUnides() As String
            Get
                Return Me.gercenUnidesField
            End Get
            Set
                Me.gercenUnidesField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property GercenCodres() As String
            Get
                Return Me.gercenCodresField
            End Get
            Set
                Me.gercenCodresField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property GercenDesres() As String
            Get
                Return Me.gercenDesresField
            End Get
            Set
                Me.gercenDesresField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property GergenUnidad() As String
            Get
                Return Me.gergenUnidadField
            End Get
            Set
                Me.gergenUnidadField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property GergenUnides() As String
            Get
                Return Me.gergenUnidesField
            End Get
            Set
                Me.gergenUnidesField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property GergenCodres() As String
            Get
                Return Me.gergenCodresField
            End Get
            Set
                Me.gergenCodresField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property GergenDesres() As String
            Get
                Return Me.gergenDesresField
            End Get
            Set
                Me.gergenDesresField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property GercorUnidad() As String
            Get
                Return Me.gercorUnidadField
            End Get
            Set
                Me.gercorUnidadField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property GercorUnides() As String
            Get
                Return Me.gercorUnidesField
            End Get
            Set
                Me.gercorUnidesField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property GercorCodres() As String
            Get
                Return Me.gercorCodresField
            End Get
            Set
                Me.gercorCodresField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property GercorDesres() As String
            Get
                Return Me.gercorDesresField
            End Get
            Set
                Me.gercorDesresField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property GegcorUnidad() As String
            Get
                Return Me.gegcorUnidadField
            End Get
            Set
                Me.gegcorUnidadField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property GegcorUnides() As String
            Get
                Return Me.gegcorUnidesField
            End Get
            Set
                Me.gegcorUnidesField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property GegcorCodres() As String
            Get
                Return Me.gegcorCodresField
            End Get
            Set
                Me.gegcorCodresField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property GegcorDesres() As String
            Get
                Return Me.gegcorDesresField
            End Get
            Set
                Me.gegcorDesresField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property PrecorUnidad() As String
            Get
                Return Me.precorUnidadField
            End Get
            Set
                Me.precorUnidadField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property PrecorUnides() As String
            Get
                Return Me.precorUnidesField
            End Get
            Set
                Me.precorUnidesField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property PrecorCodres() As String
            Get
                Return Me.precorCodresField
            End Get
            Set
                Me.precorCodresField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property PrecorDesres() As String
            Get
                Return Me.precorDesresField
            End Get
            Set
                Me.precorDesresField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property CodigoAutogener() As String
            Get
                Return Me.codigoAutogenerField
            End Get
            Set
                Me.codigoAutogenerField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property LugarComercial() As String
            Get
                Return Me.lugarComercialField
            End Get
            Set
                Me.lugarComercialField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property DireccEstablec() As String
            Get
                Return Me.direccEstablecField
            End Get
            Set
                Me.direccEstablecField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property IndMecaViaje() As String
            Get
                Return Me.indMecaViajeField
            End Get
            Set
                Me.indMecaViajeField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property CwsId() As String
            Get
                Return Me.cwsIdField
            End Get
            Set
                Me.cwsIdField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property CupId() As String
            Get
                Return Me.cupIdField
            End Get
            Set
                Me.cupIdField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="urn:sap-com:document:sap:soap:functions:mc-style")>  _
    Partial Public Class ZhccpeStJornal
        
        Private pernrField As String
        
        Private jornaField As Decimal
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property Pernr() As String
            Get
                Return Me.pernrField
            End Get
            Set
                Me.pernrField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property Jorna() As Decimal
            Get
                Return Me.jornaField
            End Get
            Set
                Me.jornaField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="urn:sap-com:document:sap:soap:functions:mc-style")>  _
    Partial Public Class Zmerchandising
        
        Private sociedadField As String
        
        Private nombreSociedadField As String
        
        Private codigoField As String
        
        Private nombreField As String
        
        Private apellidoPaternoField As String
        
        Private apellidoMaternoField As String
        
        Private descDivisionPeField As String
        
        Private subdPersField As String
        
        Private fechaCumpleanosField As String
        
        Private emailTrabajoField As String
        
        Private tipoDocumentoField As String
        
        Private numeroDocumentoField As String
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property Sociedad() As String
            Get
                Return Me.sociedadField
            End Get
            Set
                Me.sociedadField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property NombreSociedad() As String
            Get
                Return Me.nombreSociedadField
            End Get
            Set
                Me.nombreSociedadField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property Codigo() As String
            Get
                Return Me.codigoField
            End Get
            Set
                Me.codigoField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property Nombre() As String
            Get
                Return Me.nombreField
            End Get
            Set
                Me.nombreField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property ApellidoPaterno() As String
            Get
                Return Me.apellidoPaternoField
            End Get
            Set
                Me.apellidoPaternoField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property ApellidoMaterno() As String
            Get
                Return Me.apellidoMaternoField
            End Get
            Set
                Me.apellidoMaternoField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property DescDivisionPe() As String
            Get
                Return Me.descDivisionPeField
            End Get
            Set
                Me.descDivisionPeField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property SubdPers() As String
            Get
                Return Me.subdPersField
            End Get
            Set
                Me.subdPersField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property FechaCumpleanos() As String
            Get
                Return Me.fechaCumpleanosField
            End Get
            Set
                Me.fechaCumpleanosField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property EmailTrabajo() As String
            Get
                Return Me.emailTrabajoField
            End Get
            Set
                Me.emailTrabajoField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property TipoDocumento() As String
            Get
                Return Me.tipoDocumentoField
            End Get
            Set
                Me.tipoDocumentoField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property NumeroDocumento() As String
            Get
                Return Me.numeroDocumentoField
            End Get
            Set
                Me.numeroDocumentoField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute(AnonymousType:=true, [Namespace]:="urn:sap-com:document:sap:soap:functions:mc-style")>  _
    Partial Public Class ConsultarUnidorgResponse
        
        Private tUnidadOrgField() As ZundOrganizativ
        
        '''<remarks/>
        <System.Xml.Serialization.XmlArrayAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified),  _
         System.Xml.Serialization.XmlArrayItemAttribute("item", Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable:=false)>  _
        Public Property TUnidadOrg() As ZundOrganizativ()
            Get
                Return Me.tUnidadOrgField
            End Get
            Set
                Me.tUnidadOrgField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute(AnonymousType:=true, [Namespace]:="urn:sap-com:document:sap:soap:functions:mc-style")>  _
    Partial Public Class ValidaTrab
        
        Private pNumeroDocumentoField As String
        
        Private pTipoDocumentoField As String
        
        Private tiTrabajadorField() As Zmerchandising
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property PNumeroDocumento() As String
            Get
                Return Me.pNumeroDocumentoField
            End Get
            Set
                Me.pNumeroDocumentoField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property PTipoDocumento() As String
            Get
                Return Me.pTipoDocumentoField
            End Get
            Set
                Me.pTipoDocumentoField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlArrayAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified),  _
         System.Xml.Serialization.XmlArrayItemAttribute("item", Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable:=false)>  _
        Public Property TiTrabajador() As Zmerchandising()
            Get
                Return Me.tiTrabajadorField
            End Get
            Set
                Me.tiTrabajadorField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute(AnonymousType:=true, [Namespace]:="urn:sap-com:document:sap:soap:functions:mc-style")>  _
    Partial Public Class ValidaTrabResponse
        
        Private tiTrabajadorField() As Zmerchandising
        
        '''<remarks/>
        <System.Xml.Serialization.XmlArrayAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified),  _
         System.Xml.Serialization.XmlArrayItemAttribute("item", Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable:=false)>  _
        Public Property TiTrabajador() As Zmerchandising()
            Get
                Return Me.tiTrabajadorField
            End Get
            Set
                Me.tiTrabajadorField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute(AnonymousType:=true, [Namespace]:="urn:sap-com:document:sap:soap:functions:mc-style")>  _
    Partial Public Class ZfmhrConsultaJornalPe
        
        Private tiJornalField() As ZhccpeStJornal
        
        '''<remarks/>
        <System.Xml.Serialization.XmlArrayAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified),  _
         System.Xml.Serialization.XmlArrayItemAttribute("item", Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable:=false)>  _
        Public Property TiJornal() As ZhccpeStJornal()
            Get
                Return Me.tiJornalField
            End Get
            Set
                Me.tiJornalField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute(AnonymousType:=true, [Namespace]:="urn:sap-com:document:sap:soap:functions:mc-style")>  _
    Partial Public Class ZfmhrConsultaJornalPeResponse
        
        Private tiJornalField() As ZhccpeStJornal
        
        '''<remarks/>
        <System.Xml.Serialization.XmlArrayAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified),  _
         System.Xml.Serialization.XmlArrayItemAttribute("item", Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable:=false)>  _
        Public Property TiJornal() As ZhccpeStJornal()
            Get
                Return Me.tiJornalField
            End Get
            Set
                Me.tiJornalField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute(AnonymousType:=true, [Namespace]:="urn:sap-com:document:sap:soap:functions:mc-style")>  _
    Partial Public Class ConsultaTrab
        
        Private areaPersonalField As String
        
        Private centroCostoField As String
        
        Private codigoField As String
        
        Private codigoAutogeneradoField As String
        
        Private divisionPersonaField As String
        
        Private estadoCivilField As String
        
        Private fechaIngresoField As String
        
        Private fechacumpleanosField As String
        
        Private nombreField As String
        
        Private numeroDocumentoField As String
        
        Private posicionField As String
        
        Private sexoField As String
        
        Private sociedadField As String
        
        Private subdivisionPersField As String
        
        Private ttrabajadorField() As Ztrabajadores
        
        Private unidadOrganizatField As String
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property AreaPersonal() As String
            Get
                Return Me.areaPersonalField
            End Get
            Set
                Me.areaPersonalField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property CentroCosto() As String
            Get
                Return Me.centroCostoField
            End Get
            Set
                Me.centroCostoField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property Codigo() As String
            Get
                Return Me.codigoField
            End Get
            Set
                Me.codigoField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property CodigoAutogenerado() As String
            Get
                Return Me.codigoAutogeneradoField
            End Get
            Set
                Me.codigoAutogeneradoField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property DivisionPersona() As String
            Get
                Return Me.divisionPersonaField
            End Get
            Set
                Me.divisionPersonaField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property EstadoCivil() As String
            Get
                Return Me.estadoCivilField
            End Get
            Set
                Me.estadoCivilField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property FechaIngreso() As String
            Get
                Return Me.fechaIngresoField
            End Get
            Set
                Me.fechaIngresoField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property Fechacumpleanos() As String
            Get
                Return Me.fechacumpleanosField
            End Get
            Set
                Me.fechacumpleanosField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property Nombre() As String
            Get
                Return Me.nombreField
            End Get
            Set
                Me.nombreField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property NumeroDocumento() As String
            Get
                Return Me.numeroDocumentoField
            End Get
            Set
                Me.numeroDocumentoField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property Posicion() As String
            Get
                Return Me.posicionField
            End Get
            Set
                Me.posicionField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property Sexo() As String
            Get
                Return Me.sexoField
            End Get
            Set
                Me.sexoField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property Sociedad() As String
            Get
                Return Me.sociedadField
            End Get
            Set
                Me.sociedadField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property SubdivisionPers() As String
            Get
                Return Me.subdivisionPersField
            End Get
            Set
                Me.subdivisionPersField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlArrayAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified),  _
         System.Xml.Serialization.XmlArrayItemAttribute("item", Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable:=false)>  _
        Public Property Ttrabajador() As Ztrabajadores()
            Get
                Return Me.ttrabajadorField
            End Get
            Set
                Me.ttrabajadorField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property UnidadOrganizat() As String
            Get
                Return Me.unidadOrganizatField
            End Get
            Set
                Me.unidadOrganizatField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute(AnonymousType:=true, [Namespace]:="urn:sap-com:document:sap:soap:functions:mc-style")>  _
    Partial Public Class ConsultaTrabResponse
        
        Private ttrabajadorField() As Ztrabajadores
        
        '''<remarks/>
        <System.Xml.Serialization.XmlArrayAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified),  _
         System.Xml.Serialization.XmlArrayItemAttribute("item", Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable:=false)>  _
        Public Property Ttrabajador() As Ztrabajadores()
            Get
                Return Me.ttrabajadorField
            End Get
            Set
                Me.ttrabajadorField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")>  _
    Public Delegate Sub ConsultarUnidorgCompletedEventHandler(ByVal sender As Object, ByVal e As ConsultarUnidorgCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class ConsultarUnidorgCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As ConsultarUnidorgResponse
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),ConsultarUnidorgResponse)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")>  _
    Public Delegate Sub ValidaTrabCompletedEventHandler(ByVal sender As Object, ByVal e As ValidaTrabCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class ValidaTrabCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As ValidaTrabResponse
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),ValidaTrabResponse)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")>  _
    Public Delegate Sub ZfmhrConsultaJornalPeCompletedEventHandler(ByVal sender As Object, ByVal e As ZfmhrConsultaJornalPeCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class ZfmhrConsultaJornalPeCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As ZfmhrConsultaJornalPeResponse
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),ZfmhrConsultaJornalPeResponse)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")>  _
    Public Delegate Sub ConsultaTrabCompletedEventHandler(ByVal sender As Object, ByVal e As ConsultaTrabCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class ConsultaTrabCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As ConsultaTrabResponse
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),ConsultaTrabResponse)
            End Get
        End Property
    End Class
End Namespace
