'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Namespace My
    
    <Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "14.0.0.0"),  _
     Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
    Partial Friend NotInheritable Class MySettings
        Inherits Global.System.Configuration.ApplicationSettingsBase
        
        Private Shared defaultInstance As MySettings = CType(Global.System.Configuration.ApplicationSettingsBase.Synchronized(New MySettings()),MySettings)
        
#Region "My.Settings Auto-Save Functionality"
#If _MyType = "WindowsForms" Then
    Private Shared addedHandler As Boolean

    Private Shared addedHandlerLockObject As New Object

    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
    Private Shared Sub AutoSaveSettings(ByVal sender As Global.System.Object, ByVal e As Global.System.EventArgs)
        If My.Application.SaveMySettingsOnExit Then
            My.Settings.Save()
        End If
    End Sub
#End If
#End Region
        
        Public Shared ReadOnly Property [Default]() As MySettings
            Get
                
#If _MyType = "WindowsForms" Then
               If Not addedHandler Then
                    SyncLock addedHandlerLockObject
                        If Not addedHandler Then
                            AddHandler My.Application.Shutdown, AddressOf AutoSaveSettings
                            addedHandler = True
                        End If
                    End SyncLock
                End If
#End If
                Return defaultInstance
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.SpecialSettingAttribute(Global.System.Configuration.SpecialSetting.WebServiceUrl),  _
         Global.System.Configuration.DefaultSettingValueAttribute("http://fsaerpdev01.dominio.ferreyros.com.pe:1080/sap/bc/srt/rfc/sap/zwshr_trabaja"& _ 
            "dor_pe/100/servicetrabajador/servicetrabajador")>  _
        Public ReadOnly Property ServicioExterno_EccService_SERVICETRABAJADOR() As String
            Get
                Return CType(Me("ServicioExterno_EccService_SERVICETRABAJADOR"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.SpecialSettingAttribute(Global.System.Configuration.SpecialSetting.WebServiceUrl),  _
         Global.System.Configuration.DefaultSettingValueAttribute("http://vhfryfpdci.hec.ferreycorp.com.pe:50000/XISOAPAdapter/MessageServlet?sender"& _ 
            "Party=&senderService=BS_FCORP_HCM_LEGACY_DEV&receiverParty=&receiverService=&int"& _ 
            "erface=SI_OS_CONSULTA_UNIDAD_ORGANIZATIVA&interfaceNamespace=https%3A%2F%2Fwww.f"& _ 
            "erreycorp.com.pe%2FHCM_LEGACY%2FConsultaTrabajadores%2FHCM_PT-I-004")>  _
        Public ReadOnly Property ServicioExterno_wsUnidadesOrganizativas_SI_OS_CONSULTA_UNIDAD_ORGANIZATIVAService() As String
            Get
                Return CType(Me("ServicioExterno_wsUnidadesOrganizativas_SI_OS_CONSULTA_UNIDAD_ORGANIZATIVAService"& _ 
                    ""),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.SpecialSettingAttribute(Global.System.Configuration.SpecialSetting.WebServiceUrl),  _
         Global.System.Configuration.DefaultSettingValueAttribute("http://vhfryfpdci.hec.ferreycorp.com.pe:50000/XISOAPAdapter/MessageServlet?sender"& _ 
            "Party=&senderService=BS_FCORP_HCM_LEGACY_DEV&receiverParty=&receiverService=&int"& _ 
            "erface=SI_OS_CONSULTA_DATOS_TRABAJADORES&interfaceNamespace=https%3A%2F%2Fwww.fe"& _ 
            "rreycorp.com.pe%2FHCM_LEGACY%2FConsultaTrabajadores%2FHCM_PT-I-004")>  _
        Public ReadOnly Property ServicioExterno_HanaService_SI_OS_CONSULTA_DATOS_TRABAJADORESService() As String
            Get
                Return CType(Me("ServicioExterno_HanaService_SI_OS_CONSULTA_DATOS_TRABAJADORESService"),String)
            End Get
        End Property
    End Class
End Namespace

Namespace My
    
    <Global.Microsoft.VisualBasic.HideModuleNameAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
    Friend Module MySettingsProperty
        
        <Global.System.ComponentModel.Design.HelpKeywordAttribute("My.Settings")>  _
        Friend ReadOnly Property Settings() As Global.ServicioExterno.My.MySettings
            Get
                Return Global.ServicioExterno.My.MySettings.Default
            End Get
        End Property
    End Module
End Namespace
